version: "3.8"

services:
  course-service:
    build: ./course-service
    ports:
      - "8081:8080"

  rating-service:
    build: ./rating-service
    ports:
      - "8082:8080"

  user-service:
    build: ./user-service
    ports:
      - "8083:8080"

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8084:8080"
